### ISSUE TITLE
sending a message using an auto message template

### ISSUE THREAD

**Issue by foobar8675** [intercom/intercom-node#101]
is it possible to grab an auto message id, then make another call with the message id and a user id to send the message?

currently sending messages looses all the formatting.

**Comment by choran** [comment]
Hi @foobar8675 Is it just the formatting that you are losing? i.e. are you able to continue a conversation with the user after the initial auto-message? I am just trying to see if you were able to carry on a simple conversation with the user via the initial auto-message? I was able to send a message using an auto-msg id. So I was wondering if this just relates to some specific formatting. Can you clarify what formatting you are losing?

**Comment by foobar8675** [comment]
yes, it is the initial formatting. after the initial message, i will need to test, but I believe so. but ideally, i would be able to send a message using a template format defined in our auto message, such that it is easier to change the messages. I attached an example

<img width="444" alt="screen shot 2016-08-08 at 10 01 01 pm" src="https://cloud.githubusercontent.com/assets/1685700/17505097/9fcf976e-5db3-11e6-8024-6ac3bf522a8b.png">
  
where if a product person wanted to change the messaging, they could do it via. however it could be sent whenever our time range dictates, since we can't send auto messages based on a time window.

**Comment by Skaelv** [comment]
Hey @foobar8675 your feature request is really interesting and we would definitely love to such an endpoints to our APIs in the future but I can't give you an ETA for this. I'm closing this issue as your request in API related and not intercom-node related.
