### ISSUE TITLE
How to get user events?

### ISSUE THREAD

**Issue by RichardJECooke** [intercom/intercom-node#102]
## Version info
  - intercom-node version: 2.8.0
  - Node version:

## Expected behavior

Calling `intercom.users.find({ user_id: userId })` returns events in `body.events` in the same way as it does for `body.custom_attributes`.

## Actual behavior

No events are in the response anywhere I can see them.

**Comment by choran** [comment]
Hi @RichardJECooke 
At the moment we dont have a default way to list events in the same way as you list users. We are looking at adding this but for now you can list the events for a user using something like:
```
client.get('/events', { type: 'user', user_id: '1234567' }, (function (d) {
    // d is the response from the server
    console.log(d)
}));
```
Does this help you with your current use case?

**Comment by Skaelv** [comment]
I'm closing as it seems #95 should solve your issue.
Feel free to open it again if it doesn't.
