### ISSUE TITLE
Add additional properties to the Error object (in particular statusCode`

### ISSUE THREAD

**Issue by janmeier** [intercom/intercom-node#106]
Currently the only way to get the actual error message, code etc. is to parse `error.message`

In my case I first check to see if a user with a given email exists - If not I create them as a lead. Checking if a user exists throws a 404, so I need to `JSON.parse(err.message)` to see if its just a 404, or some other error.

It would be nice if I could just check `error.code` / `error.statusCode`
## Version info
- intercom-node version: 2.8.0
- Node version: any
## Expected behavior

`error.code` or similar is defined
## Actual behavior

`error.message` is the only property - I have to `JSON.parse` it to get the `statusCode`
## Steps to reproduce
1. Search for a non-existent user
2. Catch the error

**Comment by csaroff** [comment]
Yeah, thanks @janmeier for documenting this.  I just ran into this today.  Javascript error handling is already pretty terrible.  Let's not add to terror!

Think of the typical user scenario...

```javascript
client.users.find({ user_id: 'my_nonexistent_user' })
.then((response) => {
  // Business logic that potentially throws
})
.catch((error) => {
  try {
    const statusCode = JSON.parse(error.message).statusCode;
    // handle statusCode 
  }
  catch(parseError) {
    // I guess it was an issue with the business logic?
  }
});

**Comment by sderickson** [comment]
In the meantime, it would be useful to document current behavior. It's unexpected that an error message property is a JSON string.

**Comment by choran** [comment]
Hi @janmeier and @sderickson 
thanks for this, that seems valid, and like you said I think for a first step might be good document this so that it is clear how you can access the error attributes.
I will try and get to this as a first step
Thanks
Cathal
