### ISSUE TITLE
Implement Scroll API

### ISSUE THREAD

**Issue by mhemmings** [intercom/intercom-node#115]
As far as I can tell, the scroll API isn't implemented?
Are there plans to implement this? I'm having to paginate through all users and I'm hitting the page limit.

**Comment by justinwalsh** [comment]
Having the same issue...

```json
{"code":"bad_request","message":"page limit reached, please use scroll API"}
```

**Comment by Skaelv** [comment]
I released the node client yesterday for the scroll api. https://github.com/intercom/intercom-node/pull/116
