### ISSUE TITLE
browser lib: can we get a promise-based browser lib

### ISSUE THREAD

**Issue by mbana** [intercom/intercom-node#118]
Is there a pure web JavaScript version of the library that is Promised-based?
If it not, could you kindly make available a version that is - I figure it is just a compile step away.

**Comment by louisremi** [comment]
This lib already supports promises: https://github.com/intercom/intercom-node#promises

**Comment by mbana** [comment]
what a browser-based version of it? would be nice if we had a direct link to the cdn on the README.

**Comment by Skaelv** [comment]
I'm closing the issue as this is already implemented. Feel free to open a PR to link to the cdn on the README :)
