### ISSUE TITLE
Readme incorrectly cites users.update method

### ISSUE THREAD

**Issue by howietl** [intercom/intercom-node#127]
There is no client.users.update method--only client.users.create. The readme incorrectly lists the former, whereas one must actually use the latter, which has UPSERT behavior, to update OR create the user.

**Comment by Skaelv** [comment]
Hey @howietl I've added this method few months ago : 
https://github.com/intercom/intercom-node/blob/master/lib/user.js#L12

**Comment by howietl** [comment]
any reason why you wouldn't add it for companies as well?

**Comment by Skaelv** [comment]
No reasons. Feel free to do it if you have some time :)
