### ISSUE TITLE
[question] Is documented which type of email templates are available?

### ISSUE THREAD

**Issue by leschekfm** [intercom/intercom-node#129]
I did not find a list of possible values to use for the template property nor a route which would allow me to query this.

My use case is, that I want to send an email with a certain style/template applied. From the intercom web app these 4 should be possible (plain, company, personal, announcement). Applying any of these strings as a param resulted in the same email sent.

## Version info
  - intercom-node version: 2.8.5
  - Node version: 7.1.0

## Expected behavior
The provided template is used for the email. 
## Actual behavior
It always uses the personal template

## Steps to reproduce
```
//Require Intercom
var Intercom = require('intercom-client');
var client = new Intercom.Client({ token: token });

// Admin initiated messages:
// Sending an email to a User
var message = {
  message_type: "email",
  subject: "Hey",
  body: "Simple email from intercom",
  template: "company",
  from: {
    type: "user",
    user_id: "582b18f6c370b6344a52b076"
  },
  to: {
    type: "user",
    user_id: "5825c98f1be52a4141905907"
  }
}

client.messages.create(message).then(function (data) {
  console.log('data: ', data.body)
})
```

## Logs
```
data: { type: 'user_message',
  id: '59464454',
  created_at: 1479224902,
  body: 'Simple email from intercom',
  message_type: 'inapp' }
```

**Comment by Skaelv** [comment]
Hey! 
From the reference doc (https://developers.intercom.com/reference#admin-initiated-conversation) you can only create `plain` and `personal` templates.

(+ in your example above you should have an admin either in `from` or in `to`)

**Comment by leschekfm** [comment]
Hi @Skaelv
thanks for the quick answer. After using an user of type admin the template property was used as expected.

So it's not possible to define custom templates and use them from the node library then?

Apart from that the documentation seems to be wrong/outdated.

> body - The content of the message. Plaintext only, HTML is not supported.

`body: "Simple email <b>from</b> intercom<p>New paragraph with image <img src=\"https://scontent-frt3-1.xx.fbcdn.net/v/t1.0-1/p50x50/14716302_704385333053712_3407876776789305_n.png?oh=a97c3f157913d8f2e938ca5fe070824f&oe=58D530B9\"></p>"`

This was properly rendered inside the email, see 
![selection_251](https://cloud.githubusercontent.com/assets/1288436/20314948/58d42b44-ab5c-11e6-8f58-41b6167a891b.png)

**Comment by Skaelv** [comment]
Hey @leschekfm so sorry for the late answer 😬 
You are right It is not possible at the moment to create message draft and use them to send messages.
Thanks! Docs have been updated 👍 
I'm closing please re-open if necessary.

**Comment by evenfrost** [comment]
@Skaelv are there any technical difficulties preventing from implementing possibility to provide custom email templates on the API level? Seems strange to me that there are only 2 default options via API, though full functionality is available at UI side.

**Comment by LukeXF** [comment]
Any updates on this? Seems odd that we can't set our custom template (which we have created already on the intercom site). Thanks guys!

**Comment by JoeyDelahoussaye** [comment]
I'm dealing with the same problem. Any updates on this? Thanks!

**Comment by LukeXF** [comment]
> I'm dealing with the same problem. Any updates on this? Thanks!

I contacted their support. Currently, they only support the two default types through their API (they passed on my comment to their platform team).

Which is a shame because I wanted to switch over from SendGrid to Intercom for our platform emailing. However, I'm having problems getting basic CSS formatting in the email working.

For Intercom being such an innovative company, they really do lack in API support. I've seen multiple issues and developers talking about their emailing API. How has this issue (and others like it) been open for two years?

You guys already support custom templates on the main site, surely it's not that much harder to add it to the API?

**Comment by Appkidd** [comment]
Our company has discontinued use of Intercom because of many areas of the API including this are still lacking. It's a real shame as we love the Intercom platform as a whole.
