### ISSUE TITLE
Expected Error as an object but received string

### ISSUE THREAD

**Issue by imvanzen** [intercom/intercom-node#130]
## Version info
  - intercom-node version: 2.8.5
  - Node version: 4.6.1

## Expected behavior
Method `events.create` throws exception with response/error data as an object.

## Actual behavior
Method `events.create` throws stringified request as a new error message.

## Steps to reproduce
Happen here:
https://github.com/intercom/intercom-node/blob/master/lib/client.js#L58

**Comment by choran** [comment]
Hi @imvanzen 
Sorry for the delay in responding, just trying to review older issues that are outstanding to check the state of them. 
Are you saying that it is just an issue with the events error handling as opposed to other error handling? i.e. other errors for other resources return object so you think this should be the same or that you think the event handling should be different from other error handling?
Thanks
Cathal

**Comment by LogansUA** [comment]
@imvanzen You receive there an Error object so you can always get original JSON response like that `const errorObject = JSON.parse(error.message);`.

**Comment by choran** [comment]
@imvanzen ... were you able to capture this with example approach noted above? Was this a general issue or just something you noticed with the events?
