### ISSUE TITLE
URGENT: "remote_created_at" on users.create started breaking 07:37 PST

### ISSUE THREAD

**Issue by lukas-gitl** [intercom/intercom-node#131]
**Important:** _Would be great if this can be fixed ASAP.
We are about to start loosing data here in the **next 12 hours**._

This might be an issue with the API and this client using deprecated functionality?

## Version info
  - intercom-node version: 2.8.5
  - Node version: v4.3.2

## Expected behavior
Can create user with "signed_up_at" value.

## Actual behavior
Receive error message saying `bad 'remote_created_at' parameter`.

## Minimal Test Case
```js
const Intercom = require('intercom-client');

const INTERCOM_APP_ID = "xxxxxx";
const INTERCOM_API_KEY = "*******************";

var client = new Intercom.Client(INTERCOM_APP_ID, INTERCOM_API_KEY);

client.users.create({
  "signed_up_at": "2016-11-24T02:51:26.363097+00:00",
  "user_id": "12345675c235883a4f0c877a32fc9dd8"
}, function (resp) {
  console.log(resp.status);
  console.log(JSON.stringify(resp.body, null, 4));
});
```

## Error Response (400)
```json
{
    "type": "error.list",
    "request_id": null,
    "errors": [
        {
            "code": "bad_request",
            "message": "bad 'remote_created_at' parameter"
        }
    ]
}
```

**Comment by lukas-gitl** [comment]
We are remapping signed_up_at to a unix timestamp now and that seems to fix this.

In the future I would much appreciate if you don't introduce breaking changes without a warning...

**Comment by mmartinic** [comment]
@lukas-gitl I'm sorry about this. I shipped a unix timestamp validator for that endpoint without realizing that people were using other date formats (these are not documented in our API docs). We reverted the change on Saturday.
