### ISSUE TITLE
Using Access token in client app safe? 

### ISSUE THREAD

**Issue by jasan-s** [intercom/intercom-node#132]
intercom docs state "Personal Access Tokens should never be shared outside of your company" .  I am integrating intercom in a React SPA, thus was concerned if its safe to disclose access token on client side.

**Comment by Skaelv** [comment]
personal access token should never be displayed on client side or someone could just grab it from your javascript code and use it.
This applies for every tokens or api keys provided by any company.
Never ever use a secret value in a client app.
