### ISSUE TITLE
Cannot find module "fs" error along with multiple other errors with webpack dev server

### ISSUE THREAD

**Issue by jasan-s** [intercom/intercom-node#133]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - intercom-node version: 2.8.5
  - Node version: 6.8.1

## Steps to reproduce
 1. when ever i require `var Intercom = require('intercom-client')`
2. the errors show up in console
## Logs
```
Uncaught Error: Cannot find module "fs"
    at webpackMissingModule (form_data.js:7)
    at Object.<anonymous> (form_data.js:7)
    at Object.<anonymous> (form_data.js:353)
    at __webpack_require__ (bootstrap 68e893c…:585)
    at fn (bootstrap 68e893c…:109)
    at Object.<anonymous> (index.js:15)
    at Object.<anonymous> (index.js:1091)
    at __webpack_require__ (bootstrap 68e893c…:585)
    at fn (bootstrap 68e893c…:109)

./~/unirest/index.js
./~/mime/mime.js
./~/mime/types.json
/~/unirest/~/form-data/lib/form_data.js
./~/unirest/~/mime-db/db.json
./~/tough-cookie/package.json
./~/request/lib/har.js...
```

**Comment by mdressman** [comment]
just experienced this myself

**Comment by gnujoow** [comment]
same error :( how do you solve it

**Comment by vincenzomerolla** [comment]
@jasan-s @mdressman @gnujoow 

It looks like the unirest package is requring the fs module on this [line](https://github.com/Mashape/unirest-nodejs/blob/master/index.js#L21).

Besides the point, I don't think this was meant to be used on the client-side. It looks like it was solely meant to be used with NodeJS on the server-side.

**Comment by mdressman** [comment]
right, i got around it by only using on the server

**Comment by Skaelv** [comment]
The intercom-node client is intended to be used only server side. Intercom API doesn't support CORS request. For client-side operations you can use the javascript SDK included with the Intercom Messenger https://developers.intercom.com/v2.0/docs/intercom-javascript
