### ISSUE TITLE
Can't find company using company_id attribute.

### ISSUE THREAD

**Issue by kgcrom** [intercom/intercom-node#140]
## Version info
  - intercom-node version: 2.8.5^
  - Node version: v6.9.2

## Expected behavior
My app's company_id type is Number, and I want to find user list in specific company(ex: company_id: 100).
I call to the listUsers API, but get the error.
I expect can do it using company_id, but intercom-node module doesn't implement it.

[Intercom developer ref: List company users](https://developers.intercom.com/reference#list-company-users)

## Actual behavior
Unhandled rejection Error

## Steps to reproduce
 1. 
```javascript
companies.listUsers({id: '100'}).then(r => {
      console.log(r);
    });
or
companies.find({id: '100'}).then(r => {
      console.log(r);
});
```

## Logs
```
Unhandled rejection Error: {"statusCode":404,"body":{"type":"error.list","request_id":"apr7l9f98ocvgbpv7dq0","errors":[{"code":"not_found","message":"Company Not Found"}]},"headers":{"cache-control":"no-cache","content-type":"application/json; charset=utf-8","date":"Thu, 26 Jan 2017 08:35:47 GMT","server":"nginx",
"set-cookie":["_mkra_ctxt=9de3915db548df5a585796b1497cab2a--404; path=/; max-age=5; HttpOnly; secure"],"status":"404 Not Found","strict-transport-security":"max-age=31557600; includeSubDomains; preload","vary":"Accept-Encoding",
"x-content-type-options":"nosniff","x-frame-options":"SAMEORIGIN","x-intercom-version":"7b241962ebd2722082d2c21c7c8dae7de99ff8e2","x-request-id":"apr7l9f98ocvgbpv7dq0","x-runtime":"0.054100","x-xss-protection":"1; mode=block","transfer-encoding":"chunked","connection":"Close"},
"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"api.intercom.io","port":443,"hostname":"api.intercom.io","hash":null,"search":null,"query":null,"pathname":"/companies/279","path":"/companies/279","href":"https://api.intercom.io/companies/279"},
"method":"get","headers":{"Content-Type":"application/json","Accept":"application/json","User-Agent":"intercom-node-client/2.0.0","authorization":"Basic ZEc5ck9qUmtNak0xWVRVMFh6WmtZMkZmTkdWak5WODVNR0pqWHpnNVpUTmpOV0U0TVRrME9Ub3hPakE9Og==","content-length":0}}}

```

If you have a plan that find data using company_id, I can make P/R.
maybe
```javascript
listUsers(params, f) {
    if (params.company_id !== undefined) {
      return this.client.get(`/companies`, {company_id: params.company_id, type: 'user'}, f);
    } else (
      return this.client.get(`/companies/${params.id}/users`, {}, f);
    }
}
```
Thank you.

**Comment by stringbeans** [comment]
curious how the test is passing when this basic behaviour doesnt work :(

**Comment by em0ney** [comment]
I experienced the same, but found I was able to search by company_id using the `listBy` method.

Going to submit a pull request anyway, also to add a delete method

**Comment by choran** [comment]
Hi @kgcrom and @em0ney 
yeah, you should be able to view a company like a user i.e. using id, name and company_id.
At the moment it is restricted to just the auto created Intercom ID.
I didnt get a chance to look at the PR yet but will take a look at it soon with a view to merging
Thanks
Cathal

**Comment by choran** [comment]
@kgcrom  @em0ney 
I just pushed the PRs there which should now enable you to do this.
So will close this issue but re-open if you notice any issues.
Thanks for this.
Catha
