### ISSUE TITLE
Geting 404 for events api call

### ISSUE THREAD

**Issue by AlmogRnD** [intercom/intercom-node#145]
I'm getting 404 when I try to send a custom event 
Here is my code 
``` 
doc.profileIds.forEach(function(profileIds) {
    console.log(profileIds);
      let profile = Profiles.findOne({_id:profileIds});
      console.log(profile.email);
    
      client.events.create({
      event_name: 'loop started',
      created_at: 1439826340,
        email: profile.email,
        metadata: {status: true}
      }, function (d) {
      console.log(d.statusCode);
      });
  });
````

**Comment by semeano** [comment]
Same here.

**Comment by Skaelv** [comment]
I was unable to reproduce with an existing user: 

```javascript
client.events.create({
      event_name: 'loop started',
      created_at: 1439826740,
        email: 'test_dx_NaN@example.com',
        metadata: {status: true}
      }, function (d) {
      console.log(d.statusCode);
      });
  });
```
returns `202`: 

![image](https://cloud.githubusercontent.com/assets/5072452/26830850/235a0e74-4ac2-11e7-8733-6a9986a5260c.png)

I'm only able to reproduce when trying to submit an event with an inexistent email: 
```javascript
client.events.create({
      event_name: 'loop started',
      created_at: 1439826740,
        email: 'test_dx_NaN@example.com',
        metadata: {status: true}
      }, function (d) {
      console.log(d.statusCode);
      });
  });
```
returns `404`.
Can you try again making sure the email you are using is associated to an existing user in intercom?

**Comment by choran** [comment]
Hi @AlmogRnD 
I am not sure if you were able to resolve this? If you are still having issue then please let us know. I will close it for now since it looks like this was no longer an issue but feel free to reopen if you are still experiencing issues.
Thanks
Cathal
