### ISSUE TITLE
Retagging a user is not showing up in intercom

### ISSUE THREAD

**Issue by jonescr3** [intercom/intercom-node#159]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - intercom-node version: intercom-client 2.8.8
  - Node version: 4.8.3

## Expected behavior
You can tag and untag as many times as you'd like using the API.

## Actual behavior
When you attempt to re-tag with a tag that once belonged to a user, intercom is not displaying that tag.

## Steps to reproduce
 1. Tag a user using tags.tag()
 2. Untag a user using tags.untag()
 3. Tag the same user using the same tag as previously used.

Intercom seems to reply with a success callback (no error); however, if you check on intercom the tag is not there again for the user.  It only appears correctly the first time.

**Comment by choran** [comment]
Hi @jonescr3 
I was wondering if you were still having an issue here? 
I tried to reproduce it but it seems to work fine. In the user window I see the three activities, Tagged, Untagged and Tagged. And when I click on the tag in the app settings page for company and people tags it show the person that was tagged, then they are not there and then they are correctly tagged with the same tag again.
So it seemed to work correctly.
If you want to add the example code in your steps I try and use that the reproduce it
Thanks
Cathal

**Comment by choran** [comment]
Just closing this for now.
Please re-open if you are still having an issue here.
Thanks
Cathal
