### ISSUE TITLE
How to set http proxy ?

### ISSUE THREAD

**Issue by phagunbaya** [intercom/intercom-node#161]
## Version info
  - intercom-node version: 2.8.5
  - Node version: 7.10.1

What is the way to set http proxy url ?

**Comment by choran** [comment]
Hi @phagunbaya,
I am not sure of the context here.
Is this related to the node sdk or some other use case you are trying to resolve?
Thanks
Cathal

**Comment by phagunbaya** [comment]
This is specific to the node-sdk. I want to send intercom message from behind a proxy. In other to do that, this sdk should use environment variable "HTTPS_PROXY" or "HTTP_PROXY". Currently, it does not.

**Comment by choran** [comment]
Do you mean the request.proxy option noted here [here](http://unirest.io/nodejs.html)? 
I have not used that before but I think I know what you mean now.
e.g. I was just looking and saw some examples like [this](https://jjasonclark.com/how-to-setup-node-behind-web-proxy/) but you cannot wrap the SDK in this client since the URL is hard coded.
Is that correct? i.e. you cannot use another proxy client to set this up with the Intercom node SDK?

**Comment by phagunbaya** [comment]
@choran Yes that's the option I was referring to. You don't have to hardcode anything. If someone needs support for proxy they will set environment variables "HTTPS_PROXY" or "HTTP_PROXY". And these environment variables are standard variables which even OS understands.

I would encourage to use request node module because that library by default has support for http proxy and understands how to interpret "HTTPS_PROXY" or "HTTP_PROXY" environment variable.

**Comment by choran** [comment]
@phagunbaya cool. Like I said I have not used that before but that seems to make sense alright.
If you have any experience with this yourself please feel free to add a PR and I can review it. It is always best when someone from the community with specific experience with a particular area updates the code. 
But if not it sounds like something we should get to ourselves, I just cant be sure about when at the moment. So I will leave this open in the meantime as a way to track this.
Thanks
Cathal

**Comment by choran** [comment]
Hi @phagunbaya, I was looking into this and it looks like the version of the request node module we use should support this. We tried it here and it seems to work. Can you let me know what error you were seeing when you were trying to set this up? 
We are using the request node module you mentioned so this should work.

I will close this now and please re-open this if you are still experiencing any issues with this setup.
Thanks again for raising this.
