### ISSUE TITLE
Unable to update user's custom attribute

### ISSUE THREAD

**Issue by virtualtoy** [intercom/intercom-node#168]
## Version info
  - intercom-node version: 2.8.9
  - Node version: 8.6.0

## Expected behavior
Calling method `intercomClient.users.update()` must update user's custom attributes every time method is called. In fact looks like it fails silently after few successful calls. Please note that's a test Intercom app.

## Actual behavior
Custom attribute is not updated although `intercomClient.users.update()` result indicates the opposite

## Steps to reproduce
 1. call `intercomClient.users.update()` with an argument (example) `{user_id: 'Some user id', custom_attributes:{JIBBLES_TOTAL: 10}}`
 2. `intercomClient.users.update()` result shows that attribute was set (user's attribute is `custom_attributes:{JIBBLES_TOTAL: 10}`), but in fact it wasn't

**Comment by virtualtoy** [comment]
Some more info on this: I'm trying to implement counter - fetching intercom user first, then incrementing some attribute and saving it again. Could it be happening because of some latency?

**Comment by choran** [comment]
Hi @virtualtoy 
Could you send me on some example code with the exact way you are implementing the counter just so I can be sure I am testing it correctly?
I just verified that it worked when I tried to update a customer attribute multiple times
```
client.users.update({
  user_id: usr_id,
  custom_attributes: {
    update: 'upd1'
  }
}, function (rsp){
  console.log(rsp.body)
});
```
So I just wanted to double check how you were performing the incrementing so I can test that?
Thanks
Cathal

**Comment by choran** [comment]
@virtualtoy 
I will close this for now but please reopen if you are still experiencing issues with this
thanks
Cathal

**Comment by obari1** [comment]
> ## Version info
> * intercom-node version: 2.8.9
> * Node version: 8.6.0
> 
> ## Expected behavior
> Calling method `intercomClient.users.update()` must update user's custom attributes every time method is called. In fact looks like it fails silently after few successful calls. Please note that's a test Intercom app.
> 
> ## Actual behavior
> Custom attribute is not updated although `intercomClient.users.update()` result indicates the opposite
> 
> ## Steps to reproduce
> 1. call `intercomClient.users.update()` with an argument (example) `{user_id: 'Some user id', custom_attributes:{JIBBLES_TOTAL: 10}}`
> 2. `intercomClient.users.update()` result shows that attribute was set (user's attribute is `custom_attributes:{JIBBLES_TOTAL: 10}`), but in fact it wasn't

**I am facing same issue** 


code: 

  c```
onst body = {
    user_id: userId,
    custom_attributes: {
      data:'123'
    }
  }
  try {
    const updateSubscription = await intercomClient.users
      .update(body)
      .catch((err) => console.log(err))
    return updateSubscription
  } catch (err) {
    console.log('INTERCOM ERROR', err.body.errors)
    return false
  }
}
```

**Comment by obari1** [comment]
> @virtualtoy
> I will close this for now but please reopen if you are still experiencing issues with this
> thanks
> Cathal

**I am facing the same issue while performing an update in intercom**

```

  const body = {
    user_id: userId,
    custom_attributes: {
      data:'123'
    }
  }
  try {
    const updateSubscription = await intercomClient.users
      .update(body)
      .catch((err) => console.log(err))
    return updateSubscription
  } catch (err) {
    console.log('INTERCOM ERROR', err.body.errors)
    return false
  }
}

```
