### ISSUE TITLE
Version 2.9.1 fails when trying to access  Unirest fields.

### ISSUE THREAD

**Issue by deiga** [intercom/intercom-node#171]
## Version info
  - intercom-node version: 2.9.1
  - Node version: 6.12.0

## Expected behavior
Warn about usage of an API which does not exist anymore

## Actual behavior
App breaks in the weirdest way possible

## Steps to reproduce
 1. Connect a client
 2. Fetch `conversationCounts`
 3. `JSON.parse(data.raw_body);`

## Logs
https://gist.github.com/deiga/b5dbec80feae0319f3fc41abe470f197

A  changelog would help a lot where you could inform users that you deprecated something. :)

**Comment by choran** [comment]
HI @deiga 
There was a PR #165 which removed unirest since it was no longer maintained and was raising potential security issues. You can read more about it in the PR. But yes, it would have been better to provide more notice of this change to avoid these type of issues.
thanks
Cathal

**Comment by choran** [comment]
I am just going to close this now. As noted we will be clearer about changes in future where features may be removed.
