### ISSUE TITLE
Create admin-originated conversation

### ISSUE THREAD

**Issue by GeoffreyPlitt** [intercom/intercom-node#174]
Hello, I don't see anything here for creating admin-originated conversations, is that possible?

**Comment by choran** [comment]
Hi @GeoffreyPlitt 
You can create an admin initiated conversation but it starts out as a message. So you would create an admin init message and then you would use the conversation to reply to it. You can see how to do this [here](https://github.com/intercom/intercom-node#messages).

We should probably just include this under the same heading, ie not messages and conversations, just one conversations section like we do in the API reference [here](https://developers.intercom.com/v2.0/reference#admin-initiated-conversation).

It is technically a different endpoint, messages and conversations but I still think it would prob be clearer under one section. Would that have helped here?

**Comment by GeoffreyPlitt** [comment]
Great response, and on second glance, I'm not sure why I missed it. Well documented, closing.
