### ISSUE TITLE
Is there a way to send a bulk of users which we want to update?

### ISSUE THREAD

**Issue by dejankorez** [intercom/intercom-node#175]
## Version info
  - intercom-node version: 2.9.1
  - Node version: 7.10.0

## Expected behavior
We want to update bulk of users with custom attributes, but we can't find documentation to do that. Is there any way to do that?

**Comment by choran** [comment]
Hi @dejankorez 
For bulk updates you can use the regular users endpoint to update all your users. If you have a large number of users you would need to ensure you stay within the rate limits but outside of that simply using the users API as you normally would is the recommended way to perform a bulk update.

Let me know if there is a particular issue you are encountering in terms of performing the update.

Regards, 
Cathal

**Comment by olegzaitsevway** [comment]
@choran please update your docs to more obvious description how to update multiple users
