### ISSUE TITLE
admins.find is inconsistent with users.find

### ISSUE THREAD

**Issue by Stigjb** [intercom/intercom-node#179]
The behavior of `admins.find` seems undocumented. I expected it to take a similar argument to `users.find`, for instance `admins.find({ id: 12345 })`, but this always results in a *404: Admin not found*.
The source code reveals that the method is supposed to be called with the id as a regular value, not inside an object, which is not obvious.
I suggest that the method should work with either `12345` or `{ id: 12345 }` as an argument, or in any case that the documentation should be added.

## Version info
  - intercom-node version: 2.9.1
  - Node version: 8.9.4

## Expected behavior

See above

## Actual behavior

See above

## Steps to reproduce

See above

**Comment by choran** [comment]
Hi @Stigjb 
I agree that ideally the find should work the same as the users find.
For not though I think it is a good call out that we should first document they way that it does work
I have updated the readme with an example 
Thanks for identifying this


Cathal
