### ISSUE TITLE
manifest for cathalhoran/intercom-node:latest not found

### ISSUE THREAD

**Issue by lottamus** [intercom/intercom-node#180]
## Version info
  - intercom-node version: latest
  - Node version: v8.9.1

## Expected behavior
`docker pull cathalhoran/intercom-node` pulls the latest docker image

## Actual behavior
`Error response from daemon: manifest for cathalhoran/intercom-node:latest not found`

## Steps to reproduce
 1.  Run `docker pull cathalhoran/intercom-node`

## Logs

![image](https://user-images.githubusercontent.com/7423098/35571836-d55ba484-0598-11e8-879d-0ada8e088ab3.png)

**Comment by choran** [comment]
Hi @lottamus 
If you try 
```
docker pull intercom/sdk-images:node-sdk
```
That should work

This is the repo [link](https://hub.docker.com/r/intercom/sdk-images/tags/)

And this is the [docs](https://developers.intercom.com/docs/docker-sdk-environments) on it that may be helpful 

I will close this for now but let me know if you are still having issue with this.
Thanks
Cathal
