### ISSUE TITLE
Feature request: Typescript support

### ISSUE THREAD

**Issue by alexblack** [intercom/intercom-node#185]
Hi, we'd love to see types supported in Typescript, eg types like User, Conversation, etc.

**Comment by kmossco** [comment]
Hey @alexblack that's a good idea! At the moment we don't have this planned for the library as there are other things that have more priority - like reaching feature parity in all the endpoints - but definitely something we would like to revisit after that work is done.

In the mean time, if you have the availability to send us a PR with this we'll be happy to review it and add it. 👍

**Comment by jrbaudin** [comment]
@alexblack You'll find a seed of this at https://github.com/karmadev/intercom-service-js which basically is an abstraction with TypeScript definitions for the basic operations of *intercom-node*.

**Comment by alexblack** [comment]
Any update on this?

**Comment by dyatko** [comment]
@kmossco Two years later, TypeScript is a well-established good practice. It's extremely important to use a typed SDK to ensure proper integration, especially when third-party make API changes, e.g. switching to Contacts API.

![image](https://user-images.githubusercontent.com/31615495/99908716-6db9f080-2ce4-11eb-99a6-6b86bd9ecede.png)
https://madnight.github.io/githut/#/pull_requests/2020/3

**Comment by kmossco** [comment]
Hey @dyatko, I am no longer one of the maintainers of this library, but I am sure that the developers at Intercom are looking at this SDK's issues as time allows. And I agree, TypeScript would be a good addition. 👍

**Comment by vinaypuppal** [comment]
For anyone reaching here for TS support, Install this package for type definitions https://www.npmjs.com/package/@types/intercom-client

**Comment by hypeofpipe** [comment]
This issue is addressed in the beta version. Now, the SDK supports Typescript. https://github.com/intercom/intercom-node/wiki/Migration-guide#typescript
