### ISSUE TITLE
Delete custom attributes without having to delete entire environment

### ISSUE THREAD

**Issue by j-baconator** [intercom/intercom-node#188]
Currently, users can't delete custom attributes, only archive them, which still counts towards the 250 limit. It seems the only option is to delete the entire environment, and copy over the attributes we want.

This is problematic as there is no easy way to import **other important pieces**, such as campaigns we have set up. Any plans to either delete custom attributes from an existing app, or export other important things to a new one, such as campaigns? It's a huge lift for our team to get a new test environment back to all of the original configurations...

**Comment by kmossco** [comment]
Hey @j-baconator! At the moment it isn't possible to delete this data either in the UI or using the REST API, as this is something that Intercom itself doesn't support. With this in mind this is not possible to achieve with this library, so it's not something we can add to it.

What I recommend is to reach out to our support team in Intercom as there are a few things we can try doing such as increasing your quota of custom attributes, but to evaluate that we need to know a bit more of your use case. 👍 

I hope this helps!
