### ISSUE TITLE
leads.create not adding tags

### ISSUE THREAD

**Issue by depyronick** [intercom/intercom-node#190]
```
intercom.leads.create({
            email: "test@test.com",
            name: "test",
            tags: [{
                name: "test"
            }]
        })
```

this code is not adding tags to created leads

**Comment by kmossco** [comment]
Hey @depyronick! At the moment it isn't possible to create and tag a user or lead record in the same request. The reason behind it is that to tag a user/lead you have to send a request to the /tags endpoint with an existing user, while the `leads.create` method sends a POST to the /contacts endpoint only. This is not a limitation of this library but rather how we have designed the API itself.

So to achieve this you can do it like this:

```javascript
intercom.leads.create({
  email: "test@test.com",
  name: "test",
})
```

Collect the id that is returned in the request and:

```javascript
client.tags.tag({ name: 'test', users: [{ id: lead.id }] }, callback);
```

This should work.

**Comment by kmossco** [comment]
Closing this as because this is how the REST API works we are not able to override it using this library.
