### ISSUE TITLE
Creating a User and Adding to a Company intermittently fails with Node SDK

### ISSUE THREAD

**Issue by ehickle** [intercom/intercom-node#192]
#### Description
One of our customer's uses the node SDK to create users. When he makes those calls, he also includes the company object the user should be a part of - which is allowed according to our API reference.

The customer noticed that almost all of the time everything works like normal, but every once in a while the customer gets created and they're not associated with the appropriate company. They do quality testing where after a month, they export their users in a CSV and compare it to their own records. In doing their comparison, there were about 30 users who didn't get the company assigned.

The biggest problem for the customer is that we return a 200 success message, even though the whole call didn't work as intended. Should we be returning something different if it's only a partially successful call so that the call can be retried programmatically?

***

#### Evidence
Log information 
```
2018-04-06T20:11:42 => request_id `b2jib0rockg87u7iftmg`
2018-04-06T20:40:19 => request_id `b2jio3vb74f03ffulnb0`
```

**Comment by choran** [comment]
Hi @ehickle 
I am guessing you mean the node SDK right when you said "One of our customer's uses the Java SDK"? Just wanted to double check that first.

From the logs there appears to be one company associated with that user? is that correct or were you trying to add more companies?
I know you noted this only occurs intermittently but it would help if you could add the node code here. I know that previously we had an issue where we were returning 200's if company data failed. But this was changed and you should get 422s now for example if you are incorrectly adding companies.

If there is an issue with adding the companies that we should be returning an error to notify users of this.

Cathal

**Comment by ehickle** [comment]
Hey @choran 

Yeah I did mean node, I just typed the wrong name in the body there 😳

I've git some more info for you! Originally opened this bug in our Intercom repo but moved it here and apparently  didn't copy everything. End of day brain I guess.


These are the calls from the customer that they noticed didn't associate the company appropriately. They passed in a company, which you saw in the logs, but the user wasn't associated at the time. Notice in the response here that the company id is MIA

[testdata.txt](https://github.com/intercom/intercom-node/files/1907597/testdata.txt)


The customer already went back and added the companies after they noticed the error, so everyone currently has a company id.


Full version of logs above:

```
 06 Apr 2018 20:11:51.959intercom-production-api-vpc.i-0e006d0ca4bff7d66 intercom-production-api-vpc-rails:I, [2018-04-06T20:11:42.578637 #818533] INFO -- : [b2jib0rockg87u7iftmg] {"method":"POST","path":"/users","format":"json","controller":"Api::V3::UsersController","action":"create","status":200,"duration":130.09,"view":0.29,"db":18.56,"app_id_code":"ntk6qi9o","client_id":"a0edfff6-f54e-4974-90a5-8304f517698d","cluster":"intercom-production-api-vpc","host":"api.intercom.io","instance_id":"i-0e006d0ca4bff7d66","release":"ea66892fba33856fc7bcb359e4cef824c72ea19f","remote_ip":"52.210.51.243","request_id":"b2jib0rockg87u7iftmg","service":"intercom_app","user_agent":"intercom-node-client/2.0.0","params":{"user_id":"55704002e5f6a9aa98570f56","email":"mgaffet@cegid.fr","name":"Marie Gaffet","custom_attributes":{"isInternal":false,"timezone":"Europe/Paris","language":"fr"},"companies":[{"company_id":"55364fe952776e7c14ee39b2"}],"user":{"user_id":"55704002e5f6a9aa98570f56","email":"mgaffet@cegid.fr","name":"Marie Gaffet","custom_attributes":{"isInternal":false,"timezone":"Europe/Paris","language":"fr"},"companies":[{"company_id":"55364fe952776e7c14ee39b2"}]}},"route_name":"api/v3/users_create","request_timestamp":"2018-04-06T20:11:42.578Z"}

06 Apr 2018 20:40:23.832intercom-production-api-vpc.i-0230ea484f2546f56 intercom-production-api-vpc-rails:I, [2018-04-06T20:40:19.281133 #410156] INFO -- : [b2jio3vb74f03ffulnb0] {"method":"POST","path":"/users","format":"json","controller":"Api::V3::UsersController","action":"create","status":200,"duration":151.05,"view":0.19,"db":21.58,"app_id_code":"ntk6qi9o","client_id":"a0edfff6-f54e-4974-90a5-8304f517698d","cluster":"intercom-production-api-vpc","host":"api.intercom.io","instance_id":"i-0230ea484f2546f56","release":"8cbf775075734e2c40edcea0165a12a9484e59f6","remote_ip":"54.154.41.44","request_id":"b2jio3vb74f03ffulnb0","service":"intercom_app","user_agent":"intercom-node-client/2.0.0","params":{"user_id":"55af49d78e5a9beeb2106595","email":"trygve@wergeland.com","name":"Trygve Wergeland","custom_attributes":{"isInternal":false,"timezone":"Europe/Oslo","language":"en"},"companies":[{"company_id":"55af497a8e5a9beeb2106591"}],"user":{"user_id":"55af49d78e5a9beeb2106595","email":"trygve@wergeland.com","name":"Trygve Wergeland","custom_attributes":{"isInternal":false,"timezone":"Europe/Oslo","language":"en"},"companies":[{"company_id":"55af497a8e5a9beeb2106591"}]}},"route_name":"api/v3/users_create","request_timestamp":"2018-04-06T20:40:19.281Z"}
```


#### App details 



**APP ID**: 179566 / q02agpgf
**Admin ID (who reported issue)**: 1724482
**Can Impersonate?**: Access Not Requested / Admin Disallowed
**Conversation with Customer**: https://intercomrades.intercom.com/a/apps/tx2p130c/inbox/inbox/1463498/conversations/15670810889

**Comment by choran** [comment]
closing this since it does not seem to be a node specific issue
