### ISSUE TITLE
Add support for user deletion

### ISSUE THREAD

**Issue by thewheat** [intercom/intercom-node#194]
Docs:  https://developers.intercom.com/v2.0/reference#delete-users

**Comment by vhmth** [comment]
Yep we're gonna need this for GDPR.

**Comment by rhodgkins** [comment]
@choran do you mind if I create a PR for this?

Regarding naming/implementation - would it be OK to create a `client.users.archive` function which duplicates the current `client.users.delete` function and then update the docs accordingly. This would then mean its clear what the `.archive` function does (we could add a link to [the docs](https://developers.intercom.com/v2.0/reference#archive-a-user)) while not changing functionality for existing users (it can then be removed in a major release - perhaps when the callbacks are sorted out 😃 ).
Then for the permanent deletion add a `client.users.requestDeletion(intercomUserId)` function? Maybe it would be better as `.requestPermanentDeletion` - yes it's a bit more wordy but a bit clearer!

**Comment by JohanBengtsson** [comment]
I would love this feature as well!
