### ISSUE TITLE
intercom-node >= 2.9.3 always throws errors with default `Response error` messaging

### ISSUE THREAD

**Issue by randytarampi** [intercom/intercom-node#200]
Seems like a regression in #191. I think the last expression on the end there needs to be `'message' in res.body.errors[0]`?

https://github.com/intercom/intercom-node/blob/496e1373f8f08fbb2a107f884109d255363ba068/lib/client.js#L148

I'm seeing a bunch of these errors since the new version was pushed, and things are a bit noisy in our logs 'cause we were catching a few intercom errors based on the `message` of the `Error` returned in the callback on L158.

**Comment by choran** [comment]
This should be resolved now with latest release [v2.10.1](https://github.com/intercom/intercom-node/releases/tag/v2.10.1)
thanks 👍
