### ISSUE TITLE
Support for Access token?

### ISSUE THREAD

**Issue by luisfpinto** [intercom/intercom-node#204]
From the intercom site: 
"Warning: API Keys are being deprecated - you should use an Access token instead
Learn more about API Keys deprecation"

Are you planning to add Access token support for the library?

**Comment by olane** [comment]
Access tokens are already supported - from the readme:

### Usage

Require Intercom:

`var Intercom = require('intercom-client');`

Create a client:
#### Using Access Tokens

`var client = new Intercom.Client({ token: 'my_token' });`
