### ISSUE TITLE
Critical security vulnerabilities in dependencies: cryptiles, sshpk, stringstream

### ISSUE THREAD

**Issue by lukewlms** [intercom/intercom-node#230]
## Version info
  - intercom-node version: latest (2.10.4)
  - Node version: 11

## Expected behavior
`yarn audit` finds no mod or high-pri vulnerabilities

## Actual behavior
Two high-pri vulnerabilities:

- cryptiles
- sshpk

<img width="592" alt="image" src="https://user-images.githubusercontent.com/19214773/55893168-22de7a00-5b8e-11e9-9bfb-855dbe492025.png">

One moderate-severity vulnerability:

- stringstream

<img width="569" alt="image" src="https://user-images.githubusercontent.com/19214773/55893333-705ae700-5b8e-11e9-9781-0130f49628bf.png">

**Comment by chrisdjali-wrld3d** [comment]
Is this ever going to be addressed?

**Comment by hypeofpipe** [comment]
This issue is addressed in the beta version.
