### ISSUE TITLE
Feature Request: Implement "Adding to group conversations" to intercom-node 

### ISSUE THREAD

**Issue by iamjon** [intercom/intercom-node#242]
Hello, 
Furthering my email conversation with Andy from intercom. (I emailed before opening the issue)
It would be great if the intercom client exposed the add user to group chat functionality currently available in the api.
https://developers.intercom.com/intercom-api-reference/reference#adding-to-group-conversations-as-admin

conversation.js would need to be adjusted with something like the following to allow this change.
`{
    key: 'addToGroup',
    value: function addToGroup(params, f) {
        const { customer, admin_id, id } = params;
        const new_params =  { customer, admin_id };
        console.log('addToGroup 1', new_params);
        return this.client.post('/conversations/' + id + '/customers', new_params, f);
    }`
Usage would be like this
`
const admin_id = 'id_would_go_here';
const customer = {};
const id = 'chat_id_here'
client.conversations.addToGroup({ admin_id, customer, id }
`
The api as it written cannot use this.client.post if the params object it gets has an id, which is why I extracted it from the params and created new_params.

I tested this code and it does work against our test environment at intercom.

I can make a pr if you guys think it's worthwhile and am happy to get any feedback/review before making it.

Best regards,
Jonathan

## Version info
  - intercom-node version:
^2.10.4
  - Node version:
v8.12.0

**Comment by hypeofpipe** [comment]
This issue is addressed in the beta version. https://github.com/intercom/intercom-node/wiki/Migration-guide#conversations
