### ISSUE TITLE
Is it maintained?

### ISSUE THREAD

**Issue by MikeKoval** [intercom/intercom-node#264]
Is it maintained and are any plans for supporting Intercom API v2 e. g. new contacts api?

Intercom customer support told me that this SDK does not support contacts api yet...
https://prnt.sc/r4zbvb

**Comment by PuKoren** [comment]
It works with me, using `leads`

`client.leads.list()` => for some reason, it returns the "contacts"

**Comment by MikeKoval** [comment]
@PuKoren 
There is no search by contacts and some other features written in docs, so I would not recommend to use it in production :)
I was supposed to use superagent to request raw requests to Intercom API v2.

**Comment by MylesWardell** [comment]
Our company is also waiting for Intercom-Node to be updated before migrating to v2.

**Comment by PuKoren** [comment]
@MikeKoval indeed I also switched to the api v2 using http, after playing a bit around this module is not so useful as the API is quite simple

**Comment by hypeofpipe** [comment]
This issue is addressed in the beta version. Now it supports the latest API - v2.X. https://github.com/intercom/intercom-node/wiki/Migration-guide#main-changes
