### ISSUE TITLE
intercomClient.users.update() is not working as expected  

### ISSUE THREAD

**Issue by obari1** [intercom/intercom-node#267]
## Version info
  - intercom-node version: 2.11.0
  - Node version: 10.16.0

## Expected behaviour
Calling method intercomClient.users.update() must update user's custom attributes every time method is called but it's not working and if I pull user from the intercom (`intercomClient.users.find({ user_id: userId })`) and updating the same user it's working fine. why not I can update intercom custom attribute without pulling it from the intercom.

## Actual behaviour
Custom attribute is not updated although intercomClient.users.update() result indicates the opposite
## Steps to reproduce
1. call
```
 intercomClient.users.update({
    user_id: userId,
    custom_attributes: {
      data:'123'
    }
  }) 

```
2) it will response you 200 but it will not update in intercom

**Comment by lloydliyu** [comment]
Hey @obari1 :wave:

If you're receiving a success response, it is unlikely that this is an issue with the SDK as such, and may be an issue with the REST API or product itself. If you're still running into issues here, and you haven't already, I'd recommend reaching out to the support team using the Messenger on https://intercom.com.

Closing this out as it is unlikely an issue with the SDK itself.
