### ISSUE TITLE
Always getting http satus 401

### ISSUE THREAD

**Issue by ppbntl19** [intercom/intercom-node#27]
I am trying to get users from Intercom .
code:
```
var client = new Intercom.Client(appId,apiKey);
client.users.create({ email: 'jayne@serenity.io' }, function (response) {
      console.log(response);
    });
```
I am using api key and Id which have Read & Write access. 
But we are getting back https status 401
```
 {"type":"error.list","request_id":"aacda07a-b315-4a58-a800-046efb118dbb","errors":[{"code":"token_not_found","message":"Unauthorized 
"}]}].
```
Please help.:) 
Thanks

**Comment by oitozero** [comment]
@ppbntl19 Having the same issue. Did you solve it? Thx

**Comment by ppbntl19** [comment]
@oitozero  this is not an issue anymore. its already fixed. What version you using?

**Comment by oitozero** [comment]
@ppbntl19 Using latest version v2.8.7. 

The only diff is that now it should use a token instead of Application ID and ApplicationKey.
```
var client = new Intercom.Client({ token: '[TOKEN]' });
```
