### ISSUE TITLE
client.events.create shows an error and doesn't create the event in Intercom

### ISSUE THREAD

**Issue by JosephScript** [intercom/intercom-node#273]
## Version info
  - intercom-node version: 2.11.0
  - Node version: 14.1.0

## Expected behavior

Event should be created in Intercom.

## Actual behavior

No event is created in Intercom.

## Steps to reproduce
 1. Run `client.events.create`:

```js
client.events.create(
      {
        event_name: 'sample-event',
        created_at: Math.round(new Date().getTime() / 1000),
        user_id: user.id,
        metadata: {
            sampleId: 'sample'
        }
      },
      (err, d) => handleCallback(err, d)
    )
```

 2. Get error, no event created

## Logs

`parameter_not_found missing data parameter `

**Comment by juansobral** [comment]
Same issue here, this doesn't look like an official SDK

**Comment by DominikVavra** [comment]
Same here :)

**Comment by hypeofpipe** [comment]
Thank you for creating the issue. Is it still occurs?

**Comment by miguel-nova-credit** [comment]
This was still an issue today, but I managed to get it working by using camelCase as the parameter keys (so `eventName` instead of `event_name`), and passing in `id` instead of `userId`
