### ISSUE TITLE
Updating custom_attributes

### ISSUE THREAD

**Issue by tommaso-kinoa** [intercom/intercom-node#279]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - intercom-node version: last
  - Node version: 14.16.1

## Expected behavior
I'm trying to update conversation custom_attributes via client.conversations.reply() function, but nothing happen. How are supposed to be updated custom_attributes via this API?

## Steps to reproduce
That is how I'm trying to do:

var details = {
            id: conversation_id,
            custom_attributes:{
                detailone: conversation_details.detailone,
                detailtwo: conversation_details.detailtwo
            }
        };
        client.conversations.reply(details, (data)=> {
            res.send(data.body)
        });

**Comment by hypeofpipe** [comment]
Thank you for creating the issue. Does it still occur?
