### ISSUE TITLE
Conversations API docs show admin_id as an option to `list`, but how is this used by Intercom?

### ISSUE THREAD

**Issue by dobesv** [intercom/intercom-node#280]
Looking at the README for this project, it shows an example like this:

```
client.conversations.list({ type: 'admin', admin_id: 21599 }, callback);
```

However, no such `admin_id` query parameter is documented in the intercom docs here:

https://developers.intercom.com/intercom-api-reference/reference#list-conversations

I tried using `admin_id` but it didn't seem to filter the results in any way.  That intercom API doesn't seem to support any form of filtering, you would have to use their search API:

https://developers.intercom.com/intercom-api-reference/reference#search-for-conversations

Unfortunately, the search API is not implemented in this intercom client wrapper.

**Comment by hypeofpipe** [comment]
Search API is implemented in the latest SDK version. https://github.com/intercom/intercom-node/wiki/Migration-guide#conversations
