### ISSUE TITLE
Insecure Encryption vulnerability from request@2.88.2

### ISSUE THREAD

**Issue by trmpowell** [intercom/intercom-node#283]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - intercom-node version: 2.11.2
  - Node version: 14.17.1

## Expected behavior
Snyk reports intercom-client does not have vulnerabilities.

## Actual behavior
Snyk reports intercom-client does have this low severity vulnerability.

## Steps to reproduce
run `snyk test` on an application with a dependency on `intercom-client` package.

## Logs

```
  ✗ Insecure Encryption [Low Severity][https://snyk.io/vuln/SNYK-JS-REQUEST-1314897] in request@2.88.2
    introduced by intercom-client@2.11.2 > request@2.88.2
  No upgrade or patch available
```

**Comment by normprovost** [comment]
Vulnerability has been updated with an amendment that closes it out:

```
This was deemed not a vulnerability due to the algorithm being controlled by the developer.
```

https://security.snyk.io/vuln/SNYK-JS-REQUEST-1314897
