### ISSUE TITLE
Typescript 'this' undefined

### ISSUE THREAD

**Issue by jsilva-scu** [intercom/intercom-node#284]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - intercom-node version: 
  - Node version: 14.17.4

## Expected behavior
'this' (not undefined)

## Actual behavior
'this' (is undefined)
## Steps to reproduce
Create a normal class function (this = undefined)
Create an arrow function in the class (this = whatever this is supposed to be)

## Logs
My class:
private myService: MyService;
  constructor() {
    this.myService = new MyService();
  }
   
Within this class I only have 2 functions:
  On public doSomething =  (req: Request, res: Response, next: NextFunction) => {...} 'this' works like a gem!
  On public async doSomethingElse (req: Request, res: Response, next: NextFunction) {...} 'this' is undefined!
  If you swap the doSomething to public async doSomething (req: Request, res: Response, next: NextFunction) {...} 'this' is undefined.

By the way, this is the first issue I've ever opened so please let me know if it actually here or not.

**Comment by hypeofpipe** [comment]
This issue is addressed in the beta version. Now, the SDK supports Typescript. https://github.com/intercom/intercom-node/wiki/Migration-guide#typescript
