### ISSUE TITLE
Support api.eu.intercom.io

### ISSUE THREAD

**Issue by punkle** [intercom/intercom-node#285]
## Version info
  - intercom-node version: 2.11.2
  - Node version: 14.17.3

## Expected behavior
Ability to pass the base url for the api client as api.eu.intercom.io

## Actual behavior
It may already by possible but I am not sure how.

## Steps to reproduce
N/A

## Logs
N/A

**Comment by SeanHealy33** [comment]
@punkle Howdy!

All newly generated api tokens come with some region based information in the EU. If you use them to query api.intercom.io they will automatically proxy requests to the EU api. 

api.eu.intercom.io still works though so I think it still makes sense to put your pr in :)
