### ISSUE TITLE
Potential Conflict with Version 2 and Assignment functionality

### ISSUE THREAD

**Issue by uptownhr** [intercom/intercom-node#288]
I am currently investigating on if I should implement the `intercom-node` package or create my own client to interface with the Intercom API. One functionality I need is the ability to use the assignment endpoint. However, while exploring the documentation and the client, I see a descrepancy. The v2.3 doc shows the usage of conversation/parts to create a message for assignment where as the `intercom-node` client is still using version 1 endpoint of calling conversation/reply. 

If I were to specify 2.3 as my api version, will using the `intercom-node` client fail? or will `/reply` continue to function for backward compatability? 

## Source Code
https://github.com/intercom/intercom-node/blob/master/lib/conversation.js#L12

## Documentation
https://developers.intercom.com/intercom-api-reference/reference#assign-a-conversation

## Version info
  - intercom-node version: 2.3
  - Node version: 16

**Comment by hypeofpipe** [comment]
https://github.com/intercom/intercom-node/issues/288 - TO BE CLOSED
This issue is addressed in the beta version. Now it supports the latest API - v2.X. https://github.com/intercom/intercom-node/wiki/Migration-guide#conversations
