### ISSUE TITLE
Typescript Not supported issue

### ISSUE THREAD

**Issue by UhiriweAudace** [intercom/intercom-node#293]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info

-   intercom-node version: 3.0.0
-   Node version: 14.18.0

## Expected behavior
I'm expecting to get the final build version of my app
## Actual behavior
Now it's failing with that below logs
## Steps to reproduce

1. Run npm build for nest.js project
2. 
3.

## Logs
![image](https://user-images.githubusercontent.com/45071320/151750314-b6e3a9d2-22a9-4fa8-a379-0719d1bc66c8.png)

**Comment by hypeofpipe** [comment]
Thank you for submitting the issue!

Could you create a repo with replication of the issue?

Another question: what's your Typescript version on your Nest's project?

**Comment by UhiriweAudace** [comment]
"typescript": "^3.9.3"

**Comment by hypeofpipe** [comment]
Try with Typescript `4.x` and let me know if it works

**Comment by hypeofpipe** [comment]
Your issue has been addressed in latest release – `3.0.1`. Try it out and let us know if it works with your initial Nest application :) 

https://github.com/intercom/intercom-node/releases/tag/v3.0.1

**Comment by hypeofpipe** [comment]
Closing for now. Reopen if you will have the same issue.
