### ISSUE TITLE
JavaScript SDK link

### ISSUE THREAD

**Issue by jsandov** [intercom/intercom-node#306]
## Expected behavior
When clicking the JavaScript SDK link it should take you to: https://developers.intercom.com/v2.4/docs/intercom-javascript
## Actual behavior
It takes you to: https://developers.intercom.com/
## Steps to reproduce

1. Click here
![image](https://user-images.githubusercontent.com/46768834/153088125-2b77d4eb-22d5-4ae8-b023-71999ecaa612.png)

**Comment by hypeofpipe** [comment]
Thank you for your contribution!
