### ISSUE TITLE
 client.contacts.create throws an error if second arg is not defined

### ISSUE THREAD

**Issue by matsilva** [intercom/intercom-node#31]
The main reason I am submitting this is because the method actually succeeds in creating the contact, but throws an error in the application. 

Instead of me having to write an empty callback `create(userData, function (r) {})` to avoid the error.
I would prefer being able to simply leave it off `create(userData)`

<img width="1321" alt="screen shot 2015-10-02 at 8 48 43 am" src="https://cloud.githubusercontent.com/assets/4511972/10246830/9104957a-68e2-11e5-8921-f6659f0b8ad2.png">

**Comment by bobjflong** [comment]
Hmm.. basically every other function has a required callback. I think that adding surface area to the API (introducing optional callbacks) is not worth it in this case. Thoughts?

**Comment by matsilva** [comment]
Is this the only file that calls the callbacks? https://github.com/intercom/intercom-node/blob/master/lib/client.js

Could be relatively smooth to implement, so maybe the surface area isn't too bad?

Obviously this is not mission critical, more of a suggestion. So ultimately I can live with writing an empty callback func if it creates too many technical overheads.

**Comment by bobjflong** [comment]
Fixed in https://github.com/intercom/intercom-node/pull/34 and released in `1.1.4`
