### ISSUE TITLE
Missing email field in contacts.createLead

### ISSUE THREAD

**Issue by drewwatkins11** [intercom/intercom-node#315]
## Version info
-   intercom-node version: 3.1.4
-   Node version: 16

## Expected behavior
SDK users should be able to create a lead with an email address, as per [https://developers.intercom.com/intercom-api-reference/reference/create-contact](https://developers.intercom.com/intercom-api-reference/reference/create-contact)

## Actual behavior
`email` field is missing in type validation

**Comment by wootwoot1234** [comment]
I'm also not able to save an email to a lead.  @drewwatkins11 what did you end up doing to solve this for yourself?  Are you using your code in production or did you go a different path?
