### ISSUE TITLE
Not able to set intercom-version in headers for useRequestOpts

### ISSUE THREAD

**Issue by ThomasSchuller** [intercom/intercom-node#326]
## Version info

-   intercom-node version: 3.1.5
-   Node version: 14.18.2

## Expected behavior
Setting the intercom-version with:
```
const client = new Client({ tokenAuth: { token: 'my_token' } });
client.useRequestOpts({
    headers: {
        'Intercom-Version': 2.4,
    },
});
```

## Actual behavior
When using TS I get this error: 
`Type '{ 'Intercom-Version': number; }' is not assignable to type 'HeadersDefaults'.
  Object literal may only specify known properties, and ''Intercom-Version'' does not exist in type 'HeadersDefaults'.ts(2322)
index.d.ts(112, 3): The expected type comes from property 'headers' which is declared here on type 'Partial<AxiosDefaults<any>>'`

Seems like it is linked to the sub dependency axios's type HeaderDefaults.

## Steps to reproduce

1. Setup a ts node project
2. install intercom-client version 3.1.5
3. Create main.ts file and add: 
```
import { Client } from 'intercom-client';
const client = new Client({ tokenAuth: { token: 'my_token' } });
client.useRequestOpts({
    headers: {
        'Intercom-Version': 2.4,
    },
});
```

## Logs
No logs, just a lint error.

**Comment by isitgeorge** [comment]
+1 client version 3.1.5, typescript version 4.2.2

**Comment by mullwaden** [comment]
The typings for this library in general are embarrassingly bad :|

**Comment by colin-oos** [comment]
How is this still open? I'm having same issue

**Comment by colin-oos** [comment]
I believe for now you have to set it like this:
```typescript
intercom.useRequestOpts({
      headers: {
        common: {
          'Intercom-Version': 2.6,
        },
        get: {},
        head: {},
        post: {},
        delete: {},
        put: {},
        patch: {},
      }
    })
  }
  ```

**Comment by fern-support** [comment]
The latest SDK has first class support for specifying a version header. Please upgrade to 6.x.x and let us know if you still have an issue!
