### ISSUE TITLE
Inconsistent names for `unsubscribed_from_emails` field

### ISSUE THREAD

**Issue by evilive3000** [intercom/intercom-node#330]
You have an interfaces for [UpdateContactData](https://github.com/intercom/intercom-node/blob/771d0bec465d9b8f22f66e97901c66ea94954ea5/lib/contact.ts#L244) which map property `isUnsubscribedFromMails` -> `unsubscribed_from_emails`. Meanwhile in all other places where you have this field you used isUnsubscribedFromEmails (not Mails, but Emails)

**Comment by fern-support** [comment]
In version 6.x.x all the fields are referenced as `unsubscribed_from_emails`
