### ISSUE TITLE
Can't find company by company Id

### ISSUE THREAD

**Issue by SudhakarSA** [intercom/intercom-node#334]
## Version info

-   intercom-node version: 3.1.5
-   Node version: 8.12.0

## Expected behavior
Get company info by company_id. Here is my code
```
let company = await intercom.companies.find({ companyId: 123 });
```
 
## Actual behavior
Getting all companies instead of filtered company

**Comment by SeanHealy33** [comment]
Hi @SudhakarSA 

I"m able to reproduce this issue. I'll get to work on fielding a fix for this issue. It appears that we are not parsing the payloads correctly here. I'll update here as I continue to figure out what's wrong with the payloads in question :) 

Thanks for the bug report :)
