### ISSUE TITLE
Latest release 3.2.0 on npm contains no code

### ISSUE THREAD

**Issue by carlmw** [intercom/intercom-node#338]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info

-   intercom-node version: 3.2.0
-   Node version:

## Expected behavior

The `intercom-client` package can be imported as in previous versions

## Actual behavior

The `intercom-client` package contains no code

## Steps to reproduce

1. Go here https://www.npmjs.com/package/intercom-client?activeTab=explore
2. Click `dist` in the tree
3. The directory only contains `package.json` and no `index.js`

**Comment by vevepeter** [comment]
Same issue here. Looks like downgrading to v3.1.5 is the only viable option.

**Comment by SeanHealy33** [comment]
Hello @vevepeter & @carlmw thank you for the issue report. 

Apologies for the bad release of 3.2.0, I've now released 3.2.1 which contains the payloads as expected. 

NPM does not allow you to update a release after the fact so I've done a patch bump on 3.2.0 instead. 

As of 3.2.1 dist now contains the files as expected:
![Screenshot 2022-12-14 at 18 49 45](https://user-images.githubusercontent.com/6124835/207686058-8e5ff904-9a79-41cb-9391-fa5e742da187.png)
