### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by friilancer** [intercom/intercom-node#347]
<img width="1022" alt="Screenshot 2023-02-07 at 10 17 32" src="https://user-images.githubusercontent.com/22805720/217204004-ce2f5a4a-d5af-4f8a-b167-297e75bb1f36.png">
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info

-   intercom-node version: 4.0.0
-   Node version: 16.4.1

## Expected Text
```
const response = await client.tags.untagCompanies({
    tagName: 'gutenTag',
    companiesIds: ['123', '234', '456'],
});
```

## Actual Text
```
const response = await client.tags.tagCompanies({
    tagName: 'gutenTag',
    companiesIds: ['123', '234', '456'],
});
```

**Comment by colmdoyle** [comment]
Great spot @friilancer! We've opened #348 to tidy this up!

**Comment by friilancer** [comment]
Awesome!
