### ISSUE TITLE
user.update?

### ISSUE THREAD

**Issue by elliotstokes** [intercom/intercom-node#35]
I want to set some custom attributes on some existing users. Looking at the doc here updating a user is supported

https://doc.intercom.io/api/#create-or-update-user

The api doesn't have an update call but but does have the create/post. What are best practices for updating. Is it to call create again on the user?

My plan was to 

Find user
Update the custom attributes object
update user (call create on existing user object with updated custom attributes?)

**Comment by bobjflong** [comment]
@elliotstokes Correct - Intercom's "create" is actually a "create or update". 

For example, to set those custom attributes:

```node
client.users.create({
  id: 'your user id',
  custom_attributes: [ ... ]
})
```

**Comment by bobjflong** [comment]
we could alias `update` to `create` maybe, to avoid confusion

**Comment by elliotstokes** [comment]
Its fine - it might be worth updating the doc though as I was initially looking for an update method.

**Comment by djmccormick** [comment]
The docs mention an `update`, but there isn't one.
