### ISSUE TITLE
I can not create a contact user.

### ISSUE THREAD

**Issue by greg-md** [intercom/intercom-node#353]
I tried to create a user based on the example from the readme, but it was created as a lead with missing most of the params.

```node
const user = await client.contacts.createUser({
    externalId: '536e564f316c83104c000020',
    phone: '+48370044567',
    name: 'Niko Bellic',
    signedUpAt: 1638203719,
    lastSeenAt: 1638203720,
    isUnsubscribedFromEmails: true,
});
```

As a result, I got a Lead created with missing `externalId`, `signedUpAt` and `lastSeenAt`. Do I miss something?

PS: Until now our app was using v2 of the package, so now we are trying to migrate to v4, but nothing is working properly.

Also tried to send a message to an existing user, but it says that user is not found.

```node
await client.messages.create({
    from: {
        id: 500000,
        type: 'admin'
    },
    to: {
        id: '501825',
        type: 'user'
    },
    messageType: 'inapp',
    body: 'This is a test message from v4 sdk'
});
```

**Comment by colmdoyle** [comment]
Have you tried [updating the API version](https://developers.intercom.com/building-apps/docs/update-your-api-version) your app is targeting?

**Comment by greg-md** [comment]
@colmdoyle The app is still using 1.0 version.

**Comment by colmdoyle** [comment]
That's your issue. In order to use the latest SDK, you also need to use the latest API version. We could probably do a better job of documenting that.

**Comment by greg-md** [comment]
Is there a way to migrate all that without affecting existing data?

**Comment by colmdoyle** [comment]
> So if I will create another app on Developer Hub, and use the v4 sdk, would it still work with old users?

Yes, you'll just need to use the [Contacts API](https://developers.intercom.com/intercom-api-reference/reference/showcontact).

> Is there a way to migrate all that without affecting existing data?

No migration needed, just use the new endpoints.

**Comment by greg-md** [comment]
Thank you. Seems like it worked with creating new auth token for newer api version.
