### ISSUE TITLE
listing by page

### ISSUE THREAD

**Issue by elliotstokes** [intercom/intercom-node#36]
When you call user.list() it suggests that it only returns the first n items (along with a pages object to show how many other pages there are). As far as I can see though there is no way to get any other page from the api other than the first. Is there any way to list all users or get the users on the next n pages?

https://doc.intercom.io/api/#list-users

**Comment by bobjflong** [comment]
Hi @elliotstokes check this out: https://github.com/intercom/intercom-node#pagination

**Comment by elliotstokes** [comment]
brilliant cheers.

**Comment by elliotstokes** [comment]
Can you adjust the page size by any chance or is always 50?
