### ISSUE TITLE
How to import types ?

### ISSUE THREAD

**Issue by jatin510** [intercom/intercom-node#376]
Hi !
I was trying to implement crud for company and contact. And while I am trying to import the types for the following, I am not able to import the types. 

Can you please provide an example to do the same

## Version info

-   intercom-node version: latest
-   Node version: latest

```typescript
const createContact: CreateContact = {}

```

how to import this `CreateContact` type from the `intercom-node`

**Comment by colmdoyle** [comment]
`intercom-node` doesn't have a `CreateContact` type?

There's a `ContactObject` which you can access by importing it like so

`import { ContactObject } from 'intercom-client'`
