### ISSUE TITLE
Creating and Updating a Company - only companyId should be required

### ISSUE THREAD

**Issue by akherr** [intercom/intercom-node#379]
## Version info

-   intercom-node version: 4.0.0
-   Node version: 16

## Expected behavior

Using the `create` and `update` methods for the Company model should only require `companyId`.

## Actual behavior

All of the parameters in the `create` and `update` methods for the Company are required.

```
interface CreateCompanyData {
    createdAt: Timestamp;
    companyId: string;
    name: string;
    monthlySpend: number;
    plan: string;
    size: number;
    website: string;
    industry: string;
    customAttributes: JavascriptObject;
}
declare type UpdateCompanyData = CreateCompanyData;
```

This interface should reflect what is defined in the API docs, with having all but `companyId` optional.

**Comment by fern-support** [comment]
Version 6.x.x of the SDK has all the parameters as optional ([link](https://github.com/intercom/intercom-node/blob/master/src/api/resources/companies/client/requests/CreateOrUpdateCompanyRequest.ts))
