### ISSUE TITLE
Unable to build 5.0.0 with TypeScript

### ISSUE THREAD

**Issue by DemonICOLI** [intercom/intercom-node#406]
-   intercom-node version: 5.0.0
-   Node version: 20 (LTS) and TypeScript 5.4.5

## Expected behavior

Code Compiles

## Actual behavior

Trying to compile breaks with the following error message:

```
node_modules/intercom-client/dist/client.d.ts(44,20): error TS2749: 'Axios' refers to a value, but is being used as a type here. Did you mean 'typeof Axios'?`
/node_modules/intercom-client/dist/client.d.ts(66,30): error TS2749: 'Axios' refers to a value, but is being used as a type here. Did you mean 'typeof Axios'?
``` 

tsconfig.json

```
{
  "compilerOptions": {
    "outDir": "./build",
    "allowJs": true,
    "target": "ES2022",
    "module": "Node16",
    "lib": ["ES2023"],
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "Node16",
    "sourceMap": true
  }
}
```

**Comment by Eclairemoy** [comment]
Hey @DemonICOLI - Sorry to hear you ran into this issue. We're running a pilot with a new TypeScript SDK — hopefully has no compile issues!

We'd love for you to try it out and let us know what you think. Here are the details:
- [Announcement](https://github.com/intercom/intercom-node/discussions/416)
- [npm](https://www.npmjs.com/package/intercom-client/v/6.0.0-alpha)
- [Reference](https://github.com/intercom/intercom-node/blob/6.0.0-alpha/reference.md)

Please feel free to share any feedback that you have with us here or send me a message at liz.moy@intercom.io
