### ISSUE TITLE
`listAttachedTags` Method has wrong return type

### ISSUE THREAD

**Issue by skamarnath-dh** [intercom/intercom-node#407]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info

-   intercom-node version: 5.0.0
-   Node version: 20.11.1

## Expected behavior
Data type returned from the method `client.contacts.listAttachedTags` should be [[API DOC](https://developers.intercom.com/docs/references/rest-api/api.intercom.io/Contacts/listTagsForAContact/)]
```ts
{
  type: "list"
  data: TagObject[]
}
```

## Actual behavior
It instead is 
```ts
{
  type: "list"
  tags: TagObject[]
}
```

## Steps to reproduce

1. instantiate a intercome-client
2. call method `contacts.listAttachedTags` with passing a valid contact who has some tags
3. the result will have tags list in `data` not in `tags`

**Comment by Eclairemoy** [comment]
Hey @skamarnath-dh - 

Thanks for submitting this issue. We're running a pilot with a new TypeScript SDK. We'd love for you to try it out and let us know what you think. Here are the details:
- [Announcement](https://github.com/intercom/intercom-node/discussions/416)
- [npm](https://www.npmjs.com/package/intercom-client/v/6.0.0-alpha)
- [Reference](https://github.com/intercom/intercom-node/blob/6.0.0-alpha/reference.md)

Please feel free to share any feedback that you have with us here or send me a message at liz.moy@intercom.io

**Comment by fern-support** [comment]
@skamarnath-dh Here's a link to the updated interface in v6 of the SDK https://github.com/intercom/intercom-node/blob/master/src/api/types/TagList.ts. We'll close the issue for now, but let us know if the problem still persists.
