### ISSUE TITLE
API / Node client status

### ISSUE THREAD

**Issue by brynary** [intercom/intercom-node#413]
We are long time, happy Intercom customers and are excited about the new AI support features that you are working on.

As we evaluate our approach to AI, especially for customer service, we have been considering integrations systems. For example, we have content that is not stored in Intercom, which we would like to push to Intercom via API.

We code primarily in TypeScript, so we found our way here. We were surprised to find that it seems like a number of features that are available in the in-app product do not appear to be usable from the NodeJS API, for example with the Help Center client. (We were also somewhat surprised that it seemed like the NodeJS client does not appear to be actively maintained -- based on the contribution level and release history.)

Since the pace of new features around AI seems to be increasing, are there plans to invest more in exposing features via API and keeping the client libraries more in sync with the latest platform capabilities?

**Comment by Eclairemoy** [comment]
hi @brynary - we have an exciting trial run for a new TypeScript SDK. more to come later this week.

**Comment by Eclairemoy** [comment]
Hey @brynary - We're running a pilot with a new TypeScript SDK. We'd love for you to try it out and let us know what you think. Here are the details:
- [Announcement](https://github.com/intercom/intercom-node/discussions/416)
- [npm](https://www.npmjs.com/package/intercom-client/v/6.0.0-alpha)
- [Reference](https://github.com/intercom/intercom-node/blob/6.0.0-alpha/reference.md)

Please feel free to share any feedback that you have with us here or send me a message at liz.moy@intercom.io

**Comment by brynary** [comment]
@Eclairemoy thanks! From a quick read through of the announcement, this looks great. I will take a closer look this weekend

**Comment by bkniffler** [comment]
Any chance you guys could please use axiom, isomorphic fetch or global fetch instead of node-fetch? A lot of people use cloudflare workers, and node-fetch is not compatible. @Eclairemoy
