### ISSUE TITLE
Maintenance mode?

### ISSUE THREAD

**Issue by jpike88** [intercom/intercom-node#442]
I see a maintenance mode message saying it's not going through active development. Yet I see mentions of a TypeScript SDK, and a recent release of intercom-client@6.0.0-alpha1. What's the situation?

**Comment by Eclairemoy** [comment]
Hey @jpike88 - we just released 6.0.0 officially. This will be supported moving forward 🥳 We're also in the process of updating Python, Java, and PHP.

Let us know what you think when you try it!

**Comment by jpike88** [comment]
Great, I notice https://developers.intercom.com/docs/references/unstable/rest-api/api.intercom.io/contacts/showcontactbyexternalid is in unstable, very useful method, will be great to get another release going when that is finalised. Thanks
