### ISSUE TITLE
Bad typings in SDK 5.0.0

### ISSUE THREAD

**Issue by RB-Lab** [intercom/intercom-node#447]
SDK version: 5.0.0

So far found two bad typings: 
1. `ContactObject` has field `custom_attributes`, while in fact `contact.update` uses `customAttributes`
2. `ListAttachedTagsResponse` has `tags` in it, while in fact there's no `tags`, but in fact it's `data` that contains `Array<TagObject>`

**Comment by fern-support** [comment]
Version 6.x.x of the SDK is generated using the Intercom OpenAPI spec and resolves both of the typing issues! Please let us know if you encounter any issues with the upgrade.
