### ISSUE TITLE
Any plans on releasing v6?

### ISSUE THREAD

**Issue by thexpand** [intercom/intercom-node#448]
I can see that on the npm public registry, there's an `alpha` version and a few beta ones that are deprecated. I was able to install the latest (deprecated) beta by installing `intercom-client@6.0.0-beta.3` but I don't know whether it's a better idea to just wait for an official release.

In one of the GitHub discussions, the date Nov 1, 2024 was mentioned, but there hasn't been an update since and I can't see no new version out there. Are there plans on releasing v6? Are there any issues in running the beta version in a production environment?

**Comment by Eclairemoy** [comment]
Hey @thexpand! We should have the new version live by the end of this week. Thanks for your patience.

**Comment by Eclairemoy** [comment]
It's live now @thexpand! Let us know what you think
