### ISSUE TITLE
Promises support

### ISSUE THREAD

**Issue by bobjflong** [intercom/intercom-node#45]

**Comment by tejasmanohar** [comment]
If you're adventurous, I'd recommend taking a look at ES7 async functions (a.k.a. _async/await_). The `await `keyword they expose is a `.then()` handler that scoops out the resolved value for you, allowing you to write serial (not synchronous) yet asynchronous code. Any function labeled as `async` must return a `Promise`.

Let me know if you'd like any help on this issue (or another). Always looking for more open-source ES6/7 projects to contribute to and better if I actually use them, haha.

**Comment by tejasmanohar** [comment]
As per Bluebird's promisify function I mentioned earlier, here's the reference-
https://github.com/petkaantonov/bluebird/blob/master/API.md#promisepromisifyfunction-nodefunction--dynamic-receiver---function

Very very useful in my experience... and I still use Bluebird in some of my ES6 projects for the convenience methods it provides, including promisify and much more- like `P#map` for example.

**Comment by bobjflong** [comment]
I've rolled out basic support in `2.0.0`. It is optional, and the old API is not broken. I'm happy to investigate other ways of implementing it (as long as it is stable and reliable) now that the Promises API is in place.
