### ISSUE TITLE
Add error messages

### ISSUE THREAD

**Issue by bsiddiqui** [intercom/intercom-node#53]
Found two uses

Invalid use that responded with an empty response instead of something like "Error: 'message_type' must be 'email' or 'inapp'"
```js
var Intercom = require('intercom-client')
var client = new Intercom.Client('foo', 'bar').usePromises()

var message = {
  message_type: 'message', // this is an invalid type
  body: 'Hi this is a admin initiated message',
  from: {
      type: 'admin',
      id: '123'
    },
  to: {
      type: 'user',
      id: '123'
    }
}

client.messages.create(message).then(console.log)
// => no response
```

Resource not found responds with an empty response instead of something like "Error: user not found"
```js
var Intercom = require('intercom-client')
var client = new Intercom.Client('foo', 'bar').usePromises()

var message = {
  message_type: 'inapp', 
  body: 'Hi this is a admin initiated message',
  from: {
      type: 'admin',
      id: '123'
    },
  to: {
      type: 'user',
      id: '123' // not a real user
    }
}

client.messages.create(message).then(console.log)
// => no response
```

I can understand if you'd prefer to fail silently for the second issue (though it would be nice if there was a setting to make it throw an error) but I def think the first one should have an error - required key having an invalid value

**Comment by bobjflong** [comment]
@bsiddiqui are you using `.catch()` to grab the errors? See https://github.com/intercom/intercom-node/blob/master/test/client.js#L19-L22

I don't think this is well enough documented.

**Comment by bsiddiqui** [comment]
@bobjflong ah you know what that is my bad - I'd highly recommend using [Bluebird](https://github.com/petkaantonov/bluebird) for promise support. It's what stripe, lob, and many other APIs use to promisify callbacks. Much better than native implementation for many reasons - one of which is how it handles unhandled rejections.

Also check the [benchmark](https://github.com/petkaantonov/bluebird/tree/master/benchmark) - 4x faster and 3x less memory usage

Would you accept a PR to switch? Would not be a breaking change

**Comment by bobjflong** [comment]
Sure I'd take a look!

**Comment by bobjflong** [comment]
Bluebird added in `2.1.0`
