### ISSUE TITLE
[Feature Request] add user hash utility

### ISSUE THREAD

**Issue by growlsworth** [intercom/intercom-node#56]
It would be helpful to have a function like this:

```javascript
var client = new Intercom.Client({secretKey: MY_SECRET});
var userHash = client.userHash(userId);
// or
var userHash = Intercom.Util.generateUserHash({secretKey: MY_SECRET, userId: userId});
```

I know it just does this:
```javascript
var crypto = require('crypto');
var userHash = crypto.createHmac('sha256', MY_SECRET).update(userId.toString()).digest('hex');
```
but it would be helpful to not learn that.

This request comes from enabling secure mode: https://docs.intercom.io/configuring-Intercom/enable-secure-mode.

I'm a bit confused if you prefer snake or camel casing.

Thanks.

**Comment by bobjflong** [comment]
Interesting idea, thanks!

**Comment by bobjflong** [comment]
added in `2.4.0`: https://github.com/intercom/intercom-node#secure-mode

Thanks!

**Comment by growlsworth** [comment]
Thanks. It would be helpful to show how to require SecureMode. Is it:

```js
import {SecureMode} from 'intercom-client' 
```
