### ISSUE TITLE
Change the User documentation/code to take user_id as an argument, rather than ID, as well as adding email.

### ISSUE THREAD

**Issue by Sebbenbear** [intercom/intercom-node#58]
Firstly, thanks for writing a sweet API! 
Secondly, the following code would be very useful and not difficult to implement:

`//Find user by id`
`client.users.find({ id: '1234' }, callback);`

would be better represented as:

`//Find user by id`
`(client.users.find({ user_id: '1234' }, callback);`

as this would be less misleading. This would not be a difficult fix either and would be much more practical to use.

As well as the above issue, the following would be extremely useful:

`// Find user by email`
`client.users.find({ email: '1234@gmail.com' }, callback);`

It could be implemented in user.js using:

`client.get('/users/?email=${email}', {}, callback);`

Cheers!

**Comment by bobjflong** [comment]
Hi @Sebbenbear !

I think I will add more finds today. However just wanted to point something out:

```
client.users.find({ id: '1234' }, callback);
```

is different to:

```
client.users.find({ user_id: '1234' }, callback);
```

`id` is set automatically by Intercom. It is the primary key for the resource you are saving. `user_id` is an optional identifier _you_ can set. Often people store their own database ids in there. More info [here](https://doc.intercom.io/api/#user-model).

**Comment by bobjflong** [comment]
More finds in `2.2.0`: https://github.com/intercom/intercom-node#users.

Thanks!

**Comment by Sebbenbear** [comment]
Ah, I see - good point. Thanks for taking the time to do that :) Cheers.
