### ISSUE TITLE
User Agent Data not showing in Intercom

### ISSUE THREAD

**Issue by jamesdixon** [intercom/intercom-node#65]
Hi,

I'm creating leads through a form on my site using this library. In addition to email and IP Address, I'm passing along the User Agent string pulled directly from the request headers. Unfortunately, this information isn't showing up in the lead's profile.

Here's my code:

```javascript
intercomClient.contacts
            .create({
              email: userEmail,
              last_seen_ip: userIpAddress,
              user_agent_data: request.headers['user-agent']
            })
            .then(() => {
              return reply();
            })
            .catch((err) => {
              return reply(Boom.badImplementation(err));
            });
```

Here's the string coming from the headers:

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36`

And here's what I'm seeing in Intercom:

![image](https://cloud.githubusercontent.com/assets/110114/11461403/e173d1c8-96bf-11e5-9a41-82cc4af86f8d.png)

I thought it might be a format issue, but I tried the [data in the CURL Example](https://doc.intercom.io/api/?bash#user-model), but no luck.

Thanks!

**Comment by jamesdixon** [comment]
After reading through the documentation a bit more, it seems there is actually an error in the documentation. The `lead` object model is described as having a `user_agent_data` field, but in [this example](https://doc.intercom.io/api/?bash#create-lead), you'll see that the field being used is `last_seen_user_agent`. Changing my code to use that field, I am not able to see the User Agent data in the Lead's profile.

**Comment by bobjflong** [comment]
Hi @jamesdixon - the Lead model will come back with `user_agent_data` - but the field is submitted as `last_seen_user_agent` as you noted. I've added a clarifying note to the docs.
