### ISSUE TITLE
How do I create a Lead with the API... Ohhhhhhhhh

### ISSUE THREAD

**Issue by CodeTahoe** [intercom/intercom-node#69]
Please make a note that 'Leads' are actually contacts, and not users... it's hard to find the distinction in the documentation.

Cheers

**Comment by bobjflong** [comment]
Thanks @CodeTahoe will do

**Comment by CodeTahoe** [comment]
#74

**Comment by CodeTahoe** [comment]
I believe this is enough information #72.

**Comment by bobjflong** [comment]
@CodeTahoe Cheers -  I think we can actually alias `.leads` in the code to make this easier

**Comment by CodeTahoe** [comment]
This adds unnecessary (albeit a tiny amount ) overhead to your API... I think as long as it's documented, it should be no issue, but that's up to your team.
--Cheers

**Comment by bobjflong** [comment]
Fixed in `2.6.0`

**Comment by CodeTahoe** [comment]
Thanks @bobjflong  :+1:
