### ISSUE TITLE
Secure Mode

### ISSUE THREAD

**Issue by vkomodey** [intercom/intercom-node#70]
I see that there exist user_hash method, but i don't now, in which request i should put it(hash). For example, if i am trying to create user with user hash, calculated using your method(user_id as argument), response is: 
``` json
errors: [ { "code": "bad_request', message: 'bad \"user_hash\" parameter"} ]
```
My request payload:
``` json
{
    "user_id": "12345677",
    "email": "email@test.com",
    "user_hash": "calculatedHash"
}
```

**Comment by bobjflong** [comment]
Hi @vkomodey 

Secure mode is used when interacting with the javascript widget: https://docs.intercom.io/configuring-intercom/enable-secure-mode

This library is for interacting with the REST API. Could you tell us a little bit more about what you are trying to do?

**Comment by vkomodey** [comment]
@bobjflong 
Ok, i got it. 
I thought, that we should send user_hash parameter at each request(even it is rest api). thanks for explanation.
