### ISSUE TITLE
api rate limit

### ISSUE THREAD

**Issue by mderazon** [intercom/intercom-node#71]
One of the problems when using the [unofficial node lib](https://github.com/tarunc/intercom.io) (not the lib's fault) is the strict api rate limit. There's a limit of ~500 user updates per minute which is very low if you want to bulk update users.

Does this lib handles this limitation in any way?

**Comment by tejasmanohar** [comment]
Sounds like an application concern, as the library isn't context-aware of all that's happening with your keys.

**Comment by bobjflong** [comment]
Hey,

Rate limit information should be returned in the headers for every request: https://developers.intercom.io/docs/rate-limiting

> bulk update users

Use the [bulk api](https://github.com/intercom/intercom-node#bulk-users)! :smile: This lets you update many users (max 50) in a single request, which is handled asynchronously

**Comment by mderazon** [comment]
I completely agree with @tejasmanohar that if the lib is restricted by the same set of rules the api dictates then it's an app concern. I still think it's bad developer experience that we have to do all kind of throttling hacks to make an update to a non-trivial amount of users.

@bobjflong 
> Use the bulk api

the rate is 500 users / min and **not** requests / min, so bulk doesn't help at all. 10 consecutive bulk calls and I hit that limit

If you take Segment's node library for example, they have some [queue logic](https://segment.com/docs/libraries/node/#batching) baked in to throttle request to their servers, this makes it a nicer developer experience so that you don't have to worry about stuff like that.

Maybe I'll just use Segment's package to send to Intercom :-)
I wonder how they handle the calls from their servers to Intercom's api and how they bypass the limit

**Comment by mderazon** [comment]
btw, if anyone reading this wonders, the only solution in Intercom right now to handle an update to lots of users is via the import / export csv feature in the admin, which can't be automated

**Comment by bobjflong** [comment]
> the rate is 500 users / min and not requests / min, so bulk doesn't help at all. 10 consecutive bulk calls and I hit that limit

That definitely should not be the case, can you reproduce that?

**Comment by mderazon** [comment]
@bobjflong looking at some old conversation I had with one of your reps, I see that I am wrong, it's req/min and not users/min.

So you could theoretically update 25K users / min even though I remember that when I tested it I hit the wall much sooner. 

Anyway, 50 users / request is very low and in any realistic situation we'll have to build some kind of queue around it on the client. 
It's not a big deal though, still think Segment's approach is nicer, but that's the fault of the api and not the client lib

**Comment by bobjflong** [comment]
It looks like Segment's batching is client side though. Should be possible to do something like this here, even using something like: https://www.npmjs.com/browse/keyword/throttle

**Comment by mderazon** [comment]
Batching to Segment's  servers is done client side, but I guess they have to do some batching on the server side as well before sending data to Intercom to not hit the limit. I don't think that side of the integration is open source

**Comment by mderazon** [comment]
Or maybe it is 
https://github.com/segmentio/integration-intercom

**Comment by Rolice** [comment]
As far as I remember the limit was of 100 and now is reduced. I was not aware of this. Is it possible to post API change-log somewhere?

**Comment by dobesv** [comment]
Was the bulk API removed from this library?  I see it mentioned in here and in some repo commits, but not in the docs any more.

**Comment by rileylark** [comment]
It seems like the limit *is* users per second, not requests per second, and the bulk API was removed from the official docs altogether.

**Comment by AlmogCohen** [comment]
The bulk update is indeed missing greatly from this package...I'd rather not handle and write rate limiting code...
