### ISSUE TITLE
babel-eslint dependency

### ISSUE THREAD

**Issue by gossel-j** [intercom/intercom-node#76]
Hello intercom, is it normal that babel-eslint is not in devDependencies ?

**Comment by mogadanez** [comment]
+1
it force to install 10+ babel-* packages in production environment

**Comment by bobjflong** [comment]
Makes sense, thanks. Will fix once [this is sorted](https://github.com/Mashape/unirest-nodejs/issues/83).

**Comment by bobjflong** [comment]
Fixed thanks
