### ISSUE TITLE
Events with 'user_id'

### ISSUE THREAD

**Issue by jlouazel** [intercom/intercom-node#77]
Hi,

Is there any reason that events could not be sent using a `user_id`?
Since `email` are not a unique key, it could be confusing to send an event if two emails are the same.

Moreover, I don't understand this doc section:

```javascript
// Note: events will work when identified by 'email'.

// Create a event
client.events.create({
  event_name: 'Foo',
  created_at: 1439826340,
  user_id: 'bar'
}, function (d) {
  console.log(d);
});
```
Do you mean it will only work with the `email` field?

Thanks.

**Comment by bobjflong** [comment]
Hi @jlouazel - yep you can send `user_id`! Anything in the docs should work: https://developers.intercom.io/docs/submitting-events
