### ISSUE TITLE
Is there no easy way to get users.list() to support pagination?

### ISSUE THREAD

**Issue by tim-kos** [intercom/intercom-node#89]
Currently users.list() does not allow any arguments other than the callback function. How can I tell it to give me page 2, etc. ?

**Comment by bobjflong** [comment]
Hi @tim-kos - you can pass the page object returned to the `nextPage` function https://github.com/intercom/intercom-node#pagination

**Comment by michael-watson** [comment]
This no longer works, get an error that the URI isn't set. It seems you need to construct the URL and pass it as an object instead of the pages object now

**Comment by eXeDK** [comment]
@bobjflong please re-open or just state that it doesn't work anymore.

**Comment by bobjflong** [comment]
Hi, no longer a maintainer of this library (and not working at Intercom).
Thanks

**Comment by eXeDK** [comment]
Fair enough @bobjflong, thanks for the swift reply
