### ISSUE TITLE
404 error when i was calling message.create method .

### ISSUE THREAD

**Issue by medaamarnadh** [intercom/intercom-node#98]
Hi , I was getting below error when i was calling messages.create method .

Can any one explore this

`"body": {
      "type": "error.list",
      "request_id": "alnvbrgmmvv77ttsm17g",
      "errors": [
        {
          "code": "not_found",
          "message": "Resource Not Found"
        }
      ]
    },`

**Comment by bobjflong** [comment]
This mostly likely indicates that the user or admin you are referencing in the API call does not exist. Both must exist prior to sending the message. Can you confirm that? If still a problem can you provide more details about the call you are making?

**Comment by laurensnl** [comment]
Same problem here.

`		var message = {
			from: {
				type: "user",
				id: "xxx"
			},
			body: "Howdy this is a test"
		};
		
		intercomClient.messages.create(message, function(data) { console.log(data.status); });
`

Writes '404' to the console. Any suggestions?

**Comment by laurensnl** [comment]
Found the solution. 

`
var message = {
    from: {
        type: "user",
        **user_id**: "facebook:10155957623850603"
    },
    body: "Howdy this is a test"
};
`

**Comment by mhassanpur** [comment]
@laurensnl That worked! I guess the Intercom API docs need to be updated: https://developers.intercom.com/reference#user-or-contact-initiated-conversation
