### ISSUE TITLE
Remove arity detection

### ISSUE THREAD

**Issue by billinghamj** [intercom/intercom-node#99]
This isn't a bug - more a suggested deprecation.

You're currently using arity detection to decide on the behavior for callbacks. This is consistently considered bad practice in JS. I did bring it up in the PR where it was introduced (https://github.com/intercom/intercom-node/pull/18#issuecomment-193298278) but received no response.

This is particularly problematic in Node, where this is considered standard/idiomatic:

``` js
intercom.users.list(error => {
    if (error)
        log.warn('blah', [error]);
});
```

Executing the code above would result in unexpected behavior. It could be resolved by adding an unused second parameter to the function, but most linters consider this an error:

![](http://i.imgur.com/ctoyraP.png)

I'd suggest deprecating this behavior and then removing it in a future v3.

**Comment by bobjflong** [comment]
I don't understand in your example: 

```node
intercom.users.list(error => {
    if (error)
        log.warn('blah', [error]);
});
```

where you expect the result to be bound? Is the intent of your code to discard the results of the list?

**Comment by billinghamj** [comment]
Ah yes, the example was not particularly meaningful. This one makes more real-world sense:

```js
intercom.users.create({
  email: 'jayne@serenity.io',
}, error => {
  if (error)
    log.warn('blah', [error]);
});
```

**Comment by billinghamj** [comment]
But yes, the intent is to only check for the error - ignoring the actual result/output.

**Comment by choran** [comment]
Hi @billinghamj 
Just catching up on some old issue that are outstanding. As far as I know we do not plan to deprecate this. I may be wrong, I see your point and appreciate you raising it, but for now I do not think we plan to make any change here. As a result I will close this issue for now. Sorry for the delay in responding here also. 
Thanks
